### ISSUE TITLE
Repo Mountie should sign PRs

### ISSUE THREAD

**Issue by swcurran** [bcgov/repomountie#114] opened 2020-10-02 19:55 UTC
Many repos in open source communities require that all PRs be signed for DCO purposes.  For a background, see [this GitHub link](https://github.com/probot/dco#how-it-works) and this page that has the [declaration](https://developercertificate.org/). Our projects that often wind up being moved to the Linux Foundation require DCOs on all commits and it's at best a painful git exercise to retroactively sign PRs.  For now, we can accept repomountie PRs and have to manually add equivalent PRs.

Please add signing to each repo mountie PRs.  Signing in this case just means adding a blank line and name/email address to the commit message:

```
This is my commit message

Signed-off-by: Random J Developer <random@developer.example.org>
```

**Comment by jleach** [comment] 2020-10-02 19:58
@swcurran We're just rolling this feature out now. If it's still not doing this correctly LMK. 

Duplicate of #101

**Closed by jleach** 2020-10-02 19:58 UTC

**Comment by swcurran** [comment] 2020-10-02 20:08
Awesome - I should have known Wade would have put one in :-).  I should have looked in the closed issues first - doh!
