### ISSUE TITLE
Repomountie is recreating a "missing topic" issue after topic was created

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/repomountie#84] opened 2020-04-17 23:45 UTC
Following the request from repomountie to add the missing topic (https://github.com/bcgov/cas-ggircs-ciip-2018-schema/issues/22), I added it and closed the issue. However the same issue was recreated shortly after (https://github.com/bcgov/cas-ggircs-ciip-2018-schema/issues/23)

**Comment by jleach** [comment] 2020-04-24 17:34
Investigating.

**Comment by jleach** [comment] 2020-04-24 19:34
While it did create a duplicate issue, I haven't been able to reproduce this yet. 

| Time | Comment |
|04/17 12:28p | Create issue 22 |
|04/17 3:19p | Bot 5 deployed |
|04/17 3:27p | Commented and closed 22 |
|04/17 4:30p | Created issue 23 |

**Comment by matthieu-foucault** [comment] 2020-04-24 23:06
It happened with https://github.com/bcgov/cas-ciip-portal/issues/550 and  https://github.com/bcgov/cas-ciip-portal/issues/551 too. I closed 551 a couple of hours ago and it didn't create another issue, so I guess I can't reproduce it either

**Comment by jleach** [comment] 2020-04-24 23:59
I'm using [this](https://github.com/search?p=8&q=org%3Abcgov+type%3Aissue+state%3Aclosed+%22Add+missing+topics%22+created%3A2020-04-17&type=Issues) query to go through all the repos that have previously closed this issue to see if the bot is creating duplicates.

80 done so far, dupes in:
bcgov/cas-ciip-portal
bcgov/cas-ggircs-ciip-2018-schema
tire-recyceling-indicator

**Comment by WadeBarnes** [comment] 2020-05-27 15:25
I've seen this issue a couple times.  Most recently yesterday, with;
- https://github.com/bcgov/iiwbook/issues/52 - Topic (`citz`) was added, issue was closed.
- https://github.com/bcgov/iiwbook/issues/54 - A little while later `repo-mountie` added another issue.

**Comment by jleach** [comment] 2020-05-27 17:00
@WadeBarnes Thx for reporting. I saw it also in another repo so I disabled the feature late yesterday and I am refactoring the code so it only runs this logic when a repo is first created. Should be done this AM.

**Closed** 2020-05-27 20:49 UTC
Labels: bug
